CREATE TABLE users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT UNIQUE,
card_number INTEGER UNIQUE,
email TEXT,
password TEXT,
is_verified INTEGER DEFAULT 0,
otp TEXT
);

-- ACCOUNTS TABLE
CREATE TABLE accounts(
id INTEGER PRIMARY KEY AUTOINCREMENT,
account_number INTEGER UNIQUE,
status TEXT DEFAULT 'ACTIVE',
block_until TEXT
);

-- TRANSACTIONS TABLE
CREATE TABLE transactions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
account INTEGER,
amount INTEGER,
location TEXT,
timestamp TEXT
);

-- FRAUD REPORTS
CREATE TABLE fraud_reports(
id INTEGER PRIMARY KEY AUTOINCREMENT,
account INTEGER,
risk_score INTEGER,
risk_level TEXT,
action TEXT,
created_at TEXT
);
